### ISSUE TITLE
Customer App UI Visuals

### ISSUE THREAD

**Issue by jayportimo** [AWAP-6/consumer-frontend#1]
## Task list:

- [ ] Create a header with a button on the right side (this button opens a small dropdown menu?)

### Login View:

- [ ] Create a login view with two input fields for username and password
- [ ] Add "Create Account?" and "Enter" buttons

### Signup View:

- [ ] Create a Signup view with four input fields for email, username, password, and password confirmation
- [ ] Add "Login Instead?" and "Enter" buttons

### Parcel Status View:

- [ ] Create the Parcel Status view
- [ ] Add three buttons: "Ready to Pickup," "History/Delivered," and "Send New Parcel"

### Send New Parcel View:

- [ ] Create Send New Parcel view with four "sections": Parcel, Recipient, Sender, and Choose Location
- [ ] Add four input fields to parcel: Width, Height, Depth and Mass
- [ ] Add three input fields to recipient: Name, Address and Phone Number
- [ ] Add three input fields to sender: Name, Address and Phone Number
- [ ] Add five buttons "1", "2", "3", "4" and "5" to choose location
- [ ] Add "Enter" button
